baseURL = "https://eankeen.github.io/blog/"
languageCode = "en-us"
title = "Edwin's Blog"
theme = "hugo-natrium-theme"

publishDir = "docs"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

 # https://gohugohq.com/partials/emojis-shortcode-for-hugo/
enableEmoji = true
# [blackfriday]
#     enableEmoji = true

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = -130

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
